### ISSUE TITLE
Issue on player connection

### ISSUE THREAD

**Issue by Stoakes** [Lallassu/wizardwarz#3]
Hi,

I'm testing wizardwarz but I'm having an issue on connection and never reach the arena.

When I submit login form with valid credentials, server gets my request ( I see 'Player Login: nergal in console log) but I'm stuck on login page and not transported to island. 

I'm encoutering the same issue when I register a new player. Contrary to demo, I'm not moved to arena after registration. It might be a database issue because server displays 'Create new player: Toad' but no new line is added in DB.

Is there something I missed ?

**My Installation process**
- clone code
- edit js/game.js to Initialize on my host
- run server/server.js

**Browser Version** Chrome 52
*\* server*\* Debian 8 Node 0.10. with sqlite3 installed. I also tried on an Ubuntu 14 with node 4.5 but without difference.

**Comment by Lallassu** [comment]
Have you created the database?

https://github.com/Lallassu/wizardwarz/blob/master/server/server.js#L23

**Comment by Stoakes** [comment]
Yes I have.

I have also tried with repository db containing players nergal and dude

```
sqlite> .tables
players
sqlite> select * from players;
1|nergal|test|nergal@nergal.se|6|150|1|380|16|173|2014-02-18 19:12:53|2014-02-18 19:12:53
7|dude|1|dude@dude.se|9|160|1|250|22|56|2014-03-02 17:30:10|2014-03-02 17:30:10
```
