### ISSUE TITLE
error on startup server

### ISSUE THREAD

**Issue by anoni111** [Lallassu/wizardwarz#4]
i'm trying to start the server but say this on the final:

events.js:72
              throw er; // unhandled ‘error‘ event
                         ^
Error: spawn ENOENT
      at errnoExeption (child_process.js:1011:11)
      at Process.childprocess._handle.onexit (child_process.js:802:34)

---------------------------------------------------
i erase in the server/server.js  the line 20: var db = dblite('database.db') 

and the server start but when i trying to login ...Crash

My pc is Windows 7. x64
my nodejs is v0.10.33

Some fix?

**Comment by Lallassu** [comment]
I haven't really tried this for many years, but it was developed on Linux, never tested on Windows.

You cannot remove the database line as you said, that will not work since it is depending on the database.

**Comment by anoni111** [comment]
Ok, thanks for the answer
